random_forest:
  n_estimators: 100
  criterion: "gini"
  max_depth: 10            
  min_samples_split: 2
  min_samples_leaf: 5      
  max_features: "sqrt"   # Change 'auto' to 'sqrt'
  bootstrap: true
  random_state: 42
  verbose: 0
  n_jobs: -1
  class_weight: null

train_test_split:
  test_size: 0.2

k_fold:
  n_splits: 5
